services:
  - type: static_site
    name: SDPE_Tula-de-Allende
    env: static
    branch: develop
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sistemapolizasegresostulaallende.somee.com